<?php

namespace AppBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @ORM\Entity(repositoryClass="AppBundle\Repository\TagRepository")
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function createAlphabeticalQueryBuilder(){
        return $this->createAlphabeticalQueryBuilder('tag')
            ->orderBy('tag.name','ASC');
    }
}
